# Generated by Django 3.2.5 on 2021-07-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('list_book', '0003_alter_bookmodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.ManyToManyField(related_name='history_desc', to='list_book.BookModel')),
                ('image', models.ManyToManyField(related_name='history_image', to='list_book.BookModel')),
                ('title', models.ManyToManyField(related_name='history_title', to='list_book.BookModel')),
            ],
            options={
                'verbose_name': 'history',
                'verbose_name_plural': 'history',
            },
        ),
    ]
